component: "setup"
short_name: "Configure analysis"
long_name: "Configure analysis"
authors: "Rhiannon K. Owen, Naomi Bradbury, Ryan Field, Yiqiao Xin, Tom Morris, Janion Nevill, Simon Smart"
package: [BUGSnet, igraph]
