# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      'shinyscholar'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
      - run: chrome --version
        if: runner.os != 'macOS'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install JAGS (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y jags
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          
      - name: Install JAGS and rjags (Windows)
        if: runner.os == 'Windows'
        run: |
          # 1. Install JAGS
          $jagsUrl = "https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download"
          $installerPath = "$env:TEMP\JAGS.exe"
          Invoke-WebRequest -UserAgent "Wget" -Uri $jagsUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait
          
          # 2. Install rjags using the short paths
          Rscript -e "install.packages('rjags')"

      - name: Install JAGS and rjags (macOS)
        if: runner.os == 'macOS'
        run: |

          # Install JAGS with Homebrew
          # brew update
          # brew install jags
          
          # Get JAGS installation path
          # JAGS_PATH=$(brew --prefix jags)
          # echo "JAGS_PATH=$JAGS_PATH" >> $GITHUB_ENV
          

          # Install JAGS using PKG

          curl -L https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Mac%20OS%20X/JAGS-4.3.2.pkg/download -o ${{ runner.temp }}/jags.pkg
          /usr/bin/sudo installer -allowUntrusted -dumplog -pkg ${{ runner.temp }}/jags.pkg -target /

          # Install rjags with correct paths
          Rscript -e "install.packages('rjags')"
          
          # Create symlink to where rjags expects it
          # sudo mkdir -p /usr/local/lib
          # sudo mkdir -p /usr/local/lib
          # Link the whole directory
          # sudo ln -s $JAGS_PATH/lib/ /usr/local/lib/
          
          # Add JAGS to library path
          # echo "DYLD_FALLBACK_LIBRARY_PATH=$JAGS_PATH/lib:$DYLD_FALLBACK_LIBRARY_PATH" >> $GITHUB_ENV

          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck, any::XML
          pak-version: devel # See https://github.com/r-lib/actions/issues/559

      - uses: r-lib/actions/check-r-package@v2

